# Generated by Django 4.2.23 on 2025-09-30 22:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0003_tenant_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='clinic_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Clinic location as (lon,lat)', null=True, srid=4326),
        ),
    ]
